PR VUE-03 Calculate
js-tasks-ru/vue-20230320_garaev pull request #3
Opened 2023-03-25 12:23 UTC by garaev-vadim-m

2023-03-25 12:24 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-03-26 09:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-26 10:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-03-26 10:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-03-26 16:24 UTC, garaev-vadim-m commented
**@ShGKme** Выполнил все задачи из **"Основы Vue".**

2023-03-26 19:26 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` требуется избавиться от побочных эффектов в вычисляемом свойстве.

Остальные задачи приняты

2023-03-26 19:26 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>        </div>
У текстовой интерполяции принято добавлять пробелы `{{ result }}`

2023-03-26 19:26 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Вычисляемое свойство ни в коем случае не должно иметь побочных эффектов. Это вычисляемое свойство не только вычисляет результат в свойство `handler`, но и меняет состояние компонента в свойстве `result`.

Кроме того, так как вычисляемые свойства ленивые, это вычисление никогда не будет выполняться, так как нигде в приложении не используется свойство экземпляра компонента `handler`.

Делать присваивание в возврате значения в целом в JS считается плохой практикой: https://eslint.org/docs/latest/rules/no-return-assign

2023-03-26 19:26 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Вычисляемые свойства - это именно свойства. Они описываются функцией, которой Vue будет вычислять значение этого свойства. 

По этой же причине их и называют как свойства, а не как функции или методы. (handler - не звучит, как свойство хранящее значение вычисления)

2023-03-26 19:57 UTC, garaev-vadim-m commented on 01-basics/02-VueCalculator/index.html
>        </div>
Странно, по каким то причинам prettier возвращал без пробелов. Поправлю

2023-03-26 19:58 UTC, garaev-vadim-m commented on 01-basics/02-VueCalculator/script.js
> +  },
Все таки перемудрил. Отложу в голове. Изначально решил как раз через метод.

2023-03-26 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>        </div>
Prettier не влияет на текстовую интерполяцию, он в целом почти ничего не знает про специфические для Vue вещи.

2023-03-26 22:03 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Корректное решение будет через вычисляемое свойство, но это должно быть именно свойство, которое используется как свойство, и и в процессе вычисления которого нет побочных эффектов и изменения других свойств.

2023-03-27 06:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-03-27 07:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-03-27 07:07 UTC, garaev-vadim-m commented
@ShGKme в целом понял в чем была суть computed и что имел ввиду. Думаю еще не раз закреплю на практике.

2023-03-27 19:36 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-03-27 19:36 UTC, merged